### ISSUE TITLE
Errors with version 3.1.0, not with 2.1.0

### ISSUE THREAD

**Issue by reggayo** [mnlipp/jdrupes-taglets#21]
Hello, thanks for your plug in. Very helpful :-)

I tried this example:
```
/**
 * This package/class ...
 * <p>
 * <img src="example_header.svg" alt="example_header">
 * 
 * @plantUml example_header.svg 
 * Alice --> Bob: Authentication Request 
 * Bob --> Alice: Authentication Response
 */
public final class Test {

	/**
	 * This method ...
	 * <p>
	 * <img src="example_main.svg" alt="example_main">
	 * 
	 * @param args
	 * 
	 * @plantUml example_main.svg 
	 * Alice --> Bob: Authentication Request 
	 * Bob --> Alice: Authentication Response
	 */
	public static void main(String[] args) {
		System.out.println("Hello, world!");
	}
}
``` 
With version 2.1.0 this works well: I can get the 1st drawing in the class block comment, but not in the method block comment (BTW: is this the expected behaviour?).

With version 3.1.0, I got the following exception:
```` 
error: An internal exception has occurred. 
[ERROR]   	(java.lang.NoClassDefFoundError: net/sourceforge/plantuml/SourceStringReader)
[ERROR] Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR] (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com)
[ERROR] for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.NoClassDefFoundError: net/sourceforge/plantuml/SourceStringReader
[ERROR] 	at org.jdrupes.taglets.plantUml.PlantUml.processTag(PlantUml.java:131)
[ERROR] 	at org.jdrupes.taglets.plantUml.PlantUml.toString(PlantUml.java:93)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.UserTaglet.getAllBlockTagOutput(UserTaglet.java:125)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.taglets.TagletWriter.getBlockTagOutput(TagletWriter.java:288)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:365)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.getBlockTagOutput(HtmlDocletWriter.java:351)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDocletWriter.addTagsInfo(HtmlDocletWriter.java:337)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.ClassWriterImpl.addClassTagInfo(ClassWriterImpl.java:224)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassTagInfo(ClassBuilder.java:316)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassInfo(ClassBuilder.java:185)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.buildClassDoc(ClassBuilder.java:147)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.builders.ClassBuilder.build(ClassBuilder.java:113)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:376)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:286)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:199)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:212)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.doclets.toolkit.AbstractDoclet.run(AbstractDoclet.java:115)
[ERROR] 	at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.run(StandardDoclet.java:103)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] Caused by: java.lang.ClassNotFoundException: net.sourceforge.plantuml.SourceStringReader
[ERROR] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[ERROR] 	... 23 more
````
I use Eclipse (2023.09) + Maven 3.9.4 + OpenJDK build 17.0.9+9-Debian-1deb12u1

My Config for maven:
````
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.6.0</version>
 
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
        
        <configuration>
          <taglet>org.jdrupes.taglets.plantUml.PlantUml</taglet>
          <tagletArtifact>
            <groupId>org.jdrupes.taglets</groupId>
            <artifactId>plantuml-taglet</artifactId>
            <version>2.1.0</version>
          </tagletArtifact>
          <show>private</show>
          <nohelp>true</nohelp>
        </configuration>
      </plugin>
````

I am not 100% sure of my configuration. Maybe my settings are wrong for the 3.x version?

Thanks for any inputs. --Best.

**Comment by mnlipp** [comment]
You are using maven. I don't know anything about maven and do not support its usage. 

As a general remark, note that different major versions of the taglet are intended to be used with different LTS versions of the JDK. So if your setup works with 2.x, it is to be expected that it does not work with 3.x unless you switch to a different JDK in your configuration.
